apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-env
data:
  WORDPRESS_DB_HOST: mysql
  WORDPRESS_DB_USER: word_admin
  WORDPRESS_DB_PASSWORD: add0065Mysql
  WORDPRESS_DB_NAME: wordpress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-env
data:
  MYSQL_DATABASE: wordpress
  MYSQL_USER: word_admin
  MYSQL_PASSWORD: add0065Mysql
  MYSQL_ROOT_PASSWORD: add0065Mysql
